<font size="4">

<p>First, a quick (informal) decription of my academic life.</p>

<p>I did my schooling from <a href="http://www.dpsnoida.org">Delhi
Public School, Noida</a>, which is affiliated to the <a
href="http://www.cbse.nic.in">Central Board of Secondary
Education</a>. Schooling includes the 10<sup>th</sup> standard
examination (matriculation?), as well as the +2 examination. For +2,
my subjects were English (Core), Physics, Chemistry, Mathematics, and 
Computer Science.</p>

<p>After completing my schooling, I joined <a
href="http://www.cmi.ac.in/">Chennai Mathematical Institute</a> for
the B.Sc. (Hons) programme in Mathematics and Computer Science.</p>

<p>After completing my B.Sc. programme, I intend to pursue my Ph.D. in mathematics.</p>

<p> Also learn about my <a href="../areasofinterest">Academic areas of interest</a> and about my <a href="../futureplans">Future academic plans</a>.

<p>Important files:</p>
    <ul>
      <li><p><a href="whyijoinedcmi.pdf">Why I joined CMI</a></p></li>	
      <li><p><a href="coursesandgrades.pdf">Academic courses and grades (in CMI):</a> (Now includes fifth semester grades, and full list of courses planned for sixth semester): updated on January 12th, 2007</p></li>
      <li><p><a href="summercamps.pdf">Summer camps (during the last two years)</a></p></li>
      <li><p><a href="resume.pdf">Resume</a></p></li>
    </ul>

<p>Proofs:</p>
<ul>
<li><p><a href="cmimarksheet.jpg">CMI Marksheet for first four semesters</a></p></li>
</ul>

</body>