<div id="page_subject">
Resources for Math Olympiads
</div>

<br><p>.</p>


<p>Hi!</p>

<p>I intend to put up here some ways for students to figure out what the Olympiads are, how to go about preparing for them, and how studying for the Olympiads is helpful to a later life in mathematics. I've long been planning to put up a lot of articles but I've not completed too many of them.</p>

<p>From an early age, I was keen to study mathematics, and wanted to take up a career in mathematics. 
However, I was not aware of the scope for mathematics
and of how to go about establishing my credentials in the subject. 
Luckily I learnt of the Olympiads and found some good resources 
that helepd me prepare for them. I would like the knowledge of these 
resources to be available to as many people as possible.</p>

<p>To know more about my personal experiences with the Olympiads, stay tuned to my <a href="http://olympiadsandi.blogspot.com">Olympiad blog [external link]</a>.</p>

<p>My resources for the Olympiad, as of now, comprise three parts:</p>

<ul>
<li><p><b>Information on the Olympiad route</b>: from RMO to INMO to
the IMOTC to the IMO. Haven't yet prepared information personally but
I have put up some on Wikipedia. I have just prepared a list of <a href="olympiadfaqs.pdf">Frequenty Asked Questions on
Olympiads</a>. Also check the <a href="http://en.wikipedia.org/wiki/Regional_mathematical_Olympiad">RMO</a>, <a href="http://en.wikipedia.org/wiki/INMO">INMO</a> and <a href="http://en.wikipedia.org/wiki/IMOTC">IMOTC</a> pages in Wikipedia as well as information on the <a
href="http://www.bprim.org">Bhaskaracharya Pratishthana</a> page.</p>
<li><p><b>Information on how to prepare for the Olympiads</b>: This
document is <em>up</em> now: Click on <a
href="preparingforolympiads.pdf">Preparing for Olympiads</a> to
download the PDF file.</p> <p>It answers questions like: how to
prepare for the Olympiad?  What are the good books, websites, forums
and other references? How can they be best used?  This is the kind of
information that can make Olympiad math richer and more fun.</p> <p>I
keep updating this file so if you want regular updates please let me
know by email.</p></li> <li><p>My own articles and methods on
Olympiads. That's what the rest of this page is about.</p></li>
</ul>
<p>Currently, the only articles available for download are :</p>

<ul>
<li><p><a href="coincidenceproblemsandmethodsmain.pdf">Co-incidence Problems
and Methods (PDF format)</a></p></li>
<li><p><a href="touringproblems.pdf">Touring Problems : A Mathematical Approach
(PDF format)</a></p></li>
</ul>

<p>Another article that I intend to put up soon (by January 10th, 2007):</p>
<ul>
<li><p>Optimization methods in planar geometry</p></li>
</ul>
<p>Those interested in other formats
or the LaTeX source of the articles can contact me 
at my email address (vipul at cmi dot ac dot in).</p>

<p>Part of the subject material of both the articles was covered by me
in a training session for high
school students under the <a href="http://www.amtionline.com">
AMTI (Association of Mathematics Teachers of India)</a> camp,
being held in Chennai (July-October 2005).</p>

<p>The material is suited for self study for students in tenth class and above.
It is also largely accessible to younger students, but some guidance may be required
as all the necessary prerequisites may not have been covered. It may also form
a basis for classroom lectures to students. Those interested in using the material
for instruction can mail me so that I can send them an instructor's guide, for deriving
maximum mileage from the material.</p>

<p>Also available now are the <a href="amtiproblems.pdf">Miscellaneous problems
discussed in the AMTI camp (PDF format)</a>. 
These problems hav already been discussed
in the past few weeks, during the AMTI sessions. 
(The discussion has been updated last on 22nd September, 2005).
Further problem discussions shall be
incorporated into the file as required.</p>

<p>In case of any queries, comments or suggestions regarding the articles, please feel
free to contact me at vipul at cmi dot ac dot in.</p>

<p><a href="..">Back to my main page</a></p>

</body>