<font size="4">

<p>Hi!</p>

<p>I have been involved with the Mathematics Olympiad for some time. I
represented India for the International Mathematical Olympiads in 2003
and 2004 (to Japan and Greece respectively) and won Silver Medals as
India's top-scorer both times. Over the last few years, I have been
involved with Olympiad training activities. I have given some
Medalist's Sessions at the IMO Training Camps and have been involved
with training for Olympiads in Tamil Nadu region.</p>

<p>I intend to put up here some ways for students to figure out what
the Olympiads are, how to go about preparing for them, and how
studying for the Olympiads is helpful to a later life in
mathematics. I've long been planning to put up a lot of articles but
I've not completed too many of them.</p>

<p>From an early age, I was keen to study mathematics, and wanted to
take up a career in mathematics.  However, I was not aware of the
scope for mathematics and of how to go about establishing my
credentials in the subject.  Luckily I learnt of the Olympiads and
found some good resources that helped me prepare for them. I would
like the knowledge of these resources to be available to as many
people as possible.</p>

<p>I have divided my Olympiad resources into three sections:</p>

<ul>
      <li><a href="generalinformation/">General information on the Olympiad route</a></p</li>
      <li><a href="preparationinformation/">Information on how to prepare for the Olympiads</a></li>
      <li><a href="olympiadarticles/">Articles I have written for the Olympiads</a></li>
</ul>

<p><a href="..">Back to my main page</a></p>

</body>
